name: fcs_demo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  material_color_utilities: ^0.2.0
  flex_color_scheme: ^6.0.1
  dynamic_color: ^1.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # dart code metrics and extra lints
  dart_code_metrics: ^4.18.1
  # better lint
  lint: ^1.10.0




flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/google_fonts/

